In [1]:
import numpy as np
import pandas as pd

In [25]:
from test_pre_processing import *

In [27]:
def _scaling(X: np.array):
    for i in range(X.shape[1]):
        # print(f"Column {i}")
        # print(X[:, i])
        # print(f"Min: {min(X[:, i])}")
        # print(f"Max: {max(X[:, i])}")
        assert abs(min(X[:, i]) - 0) < 1e-6, "Did not scale the column correctly to get min = 0"
        assert abs(max(X[:, i]) - 1) < 1e-6, "Did not scale the column correctly to get max = 1"

In [31]:
# testing if the passed X is valid
from traceback import print_tb


orig_col = 7
X_df = random_data(col=orig_col, n=100)
X_str = "This is our data"
display(X_df)
X, Y = transform_X(X_df)

try:
    transform_X(X_str)
except ValueError as e:
    assert str(e) == "X must be a pandas dataframe"

# testing if the type is valid
true_types = ['trimap', 'pacmap', 'tsne', 'pca', 'none', None]
types = ['trimap', 'pacmap', 'tsne', 'pca', 'none', None, 'invalid']
for type in true_types:
    try:
        trans_X = transform_X(X_df, type=type)
        n_cols = trans_X.shape[1]
        # make sure that there is the correct number of columns
        if type == 'none' or type is None:
            print(type)
            print(f"the number of original columns: {orig_col}")
            print(f"the number of transformed columns: {n_cols}")
            assert n_cols == orig_col, "We have a different dim. which was not was expected"
        else:
            assert n_cols == 2, "Did not apply dim. We wanted to get back only 2 columns (2D data)"
        # check the min and max of trans_X is between 0 and 1 for all columns
        _scaling(trans_X)

    except ValueError as e:
        assert str(e) == f"Type must be one of {true_types}"

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,target
0,0.548814,0.715189,0.602763,0.544883,0.423655,0.645894,0.437587,1
1,0.891773,0.963663,0.383442,0.791725,0.528895,0.568045,0.925597,1
2,0.071036,0.087129,0.020218,0.832620,0.778157,0.870012,0.978618,0
3,0.799159,0.461479,0.780529,0.118274,0.639921,0.143353,0.944669,1
4,0.521848,0.414662,0.264556,0.774234,0.456150,0.568434,0.018790,0
...,...,...,...,...,...,...,...,...
95,0.399812,0.671383,0.344718,0.713767,0.639187,0.399161,0.431760,0
96,0.614528,0.070042,0.822407,0.653421,0.726342,0.536923,0.110477,0
97,0.405036,0.405374,0.321043,0.029950,0.737254,0.109784,0.606308,1
98,0.703217,0.634786,0.959142,0.103298,0.867167,0.029190,0.534917,0
99,0.404244,0.524184,0.365100,0.190567,0.019123,0.518150,0.842777,0

none
the number of original columns: 7
the number of transformed columns: 8

AssertionError: We have a different dim. which was not was expected